using PowerPlant.Core.Power.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PowerPlant.Core.Power
{
    public class CoalPowerPlant : IPowerPlant
    {
        /// <summary>
        /// A constant value representing how many kilowatts 
        /// would be theoretically be generated by a coal power plant per hour.
        /// </summary>
        private const int KILOWATTS_GENERATED_PER_HOUR = 67;

        private IDepositEnergy _energyDeposit;

        public CoalPowerPlant(IDepositEnergy energyStore)
        {
            _energyDeposit = energyStore;
        }

        /// <summary>
        /// Generates Kilowatts at Rate of 67 KWH Per Hour"
        /// </summary>
        /// <param name="forHours"></param>
        public void GenerateKilowattsForHour()
        {
            _energyDeposit.DepositEnergy(KILOWATTS_GENERATED_PER_HOUR);
        }

        public PollutionRate GetPollutionRate()
        {
            return PollutionRate.High;
        }

    }
}
